### ISSUE TITLE
signify verification failed

### ISSUE THREAD

**Issue by rockworldmi** [qbit/snap#25]
Hi,

I am getting this error for files bsd bsd.rd bas.mp 
"sha265: no properly formatted checksum lines found
sha265: bsd does not exist in "

Thanks,
Jay

**Comment by kmonticolo** [comment]
You need to add "-V 5.8" manually, when above problem occurs.

Kamil Monticolo
6 lip 2015 11:18 "rockworldmi" <notifications@github.com> napisał(a):

**Comment by rockworldmi** [comment]
Thanks. It worked.. Is there any changes i can make in script to resume packages download from where it stopped?

Thanks,
Jay

**Comment by qbit** [comment]
I have been wanting the same feature.. adding -C to $FTP_OPTS will cause resume.. but with the recent addition of httpd(8), it seems some mirrors don't support resume (at least in a fashion ftp(1) expects).

```
qbit@slip[0]:~λ ftp -C http://ftp3.usa.openbsd.org/pub/OpenBSD/snapshots/amd64/base58.tgz
Trying 192.43.244.161...
Requesting http://ftp3.usa.openbsd.org/pub/OpenBSD/snapshots/amd64/base58.tgz
 11% |***********                                                                                          |  6016 KB    00:32 ETA^C
http fetch aborted.
qbit@slip[1]:~λ ftp -C http://ftp3.usa.openbsd.org/pub/OpenBSD/snapshots/amd64/base58.tgz 
Trying 192.43.244.161...
Requesting http://ftp3.usa.openbsd.org/pub/OpenBSD/snapshots/amd64/base58.tgz
ftp: Server does not support resume.
  4% |****                                                                                                 |  2432 KB    00:43 ETA^C
http fetch aborted.
qbit@slip[1]:~λ 
``` 

I have a diff I will commit today that lets you specify FTP_OPTS in your .snaprc.

**Comment by qbit** [comment]
Committed - Can you guys test it out and see how it works for ya?

**Comment by rockworldmi** [comment]
Okay.. Let me try..

**Comment by qbit** [comment]
Closing this as -C is now usable!
