### ISSUE TITLE
Got to ask about game**.tgz

### ISSUE THREAD

**Issue by MindTooth** [qbit/snap#30]
Hi,

Would it be much work to make an option like `-g` to perhaps drop pulling the `game**.tgz` package?  Don't see the use pulling this when all I want is `httpd` :-)

Thanks for the script though!  Appreciated :-D

**Comment by kmonticolo** [comment]
Hi, you can just easily remove game entry from sets near:
set -A sets 'comp' 'game' 'man' 'base'
in 16th line of the script.

Regards
Kamil Monticolo
11 paź 2015 01:34 "Birger J. Nordølum" <notifications@github.com>
napisał(a):

**Comment by qbit** [comment]
A better option might be to allow custom lists of set files via cli or in ~/.snaprc

**Comment by MindTooth** [comment]
I'll try that next time, thank! :-)
