### ISSUE TITLE
script fails to update bsd.sp kernel

### ISSUE THREAD

**Issue by zmyrgel** [qbit/snap#31]
I have MP system and the script only copies the bsd.mp -> /bsd and bsd.rd -> /bsd.rd.
Problem with this is that normal upgrade using bsd.rd copies the bsd kernel to /bsd.sp which this script doesn't do. Just got burned by this as I had old bsd.sp kernel with new userland which causes issues.

Simple fix should be to add following to update_kernel function:
    cp bsd /bsd.sp || FAIL=1

**Comment by qbit** [comment]
@zmyrgel is this a machine that does MP, but you are intentionally running a SP kernel? Is the output of `sysctl -n hw.ncpufound` > 1?

**Comment by zmyrgel** [comment]
Yes, this is MP machine (Atom box). Recent changes to the em driver started to cause system freezes and I wanted to test if the problem exists with SP kernel as well. And also if the system would function with SP kernel so long as the MP-issues would get sorted out. 
The problem was that the SP kernel wasn't as up-to-date as rest of the system which caused then different panics. 

I don't think that there's any problem copying the SP kernel as /bsd.sp. This would allow MP-systems to boot SP kernel when needed. SP systems would have two kernels, /bsd and /bsd.sp.

**Comment by qbit** [comment]
I keep going back and forth between adding `bsd.mp` and `bsd.sp` kernels (along side the regular `/bsd`).. and adding a flag to just force using the sp kernel. Leaning more towards the flag..

**Comment by brycied00d** [comment]
I suggest copying both `bsd.mp` and `bsd.sp` to `/` and then copying the relevant kernel to `/bsd`. Not only does this allow a user to easily determine which kernel `/bsd` is (`ls -l /bsd*` and compare file sizes) but offers the most flexibility. It's also relatively similar to what the BSD installer does:

```sh
	if [[ -f /mnt/bsd.mp ]] && ((NCPU > 1)); then
		echo "Multiprocessor machine; using bsd.mp instead of bsd."
		mv /mnt/bsd /mnt/bsd.sp 2>/dev/null
		mv /mnt/bsd.mp /mnt/bsd
	fi
```

**Comment by qbit** [comment]
Thanks for the feedback! I also added a bit to backup the .sp kernel.
