### ISSUE TITLE
lack of test if /etc/installurl exists

### ISSUE THREAD

**Issue by kmonticolo** [qbit/snap#35]
Hi Aaron,
In case when no MIRROR is set and installurl file does not exists, you will end with error:
cat: /etc/installurl: No such file or directory

in line 314: MIRROR=$(get_conf_var 'MIRROR' || cat /etc/installurl | awk -F/ '{print $3}')
so you probably should test if file exists (test -r or -f ) before cat it.
Also "awk -F/ '{print $3}'  /etc/installurl" seems to be more elegant than simply cat the file with using pipe.
Cheers
Kamil

**Comment by qbit** [comment]
Definitely. Just out of curiosity, how does one operate without `installurl`?

**Comment by kmonticolo** [comment]
When installurl is absent, then system will get the address from PKG_PATH
variable.
I dig into pkg_add manpage and I found the right order: "If the
given package names are not
     found in the current working directory, pkg_
add will search for them in
     each directory (local or remote) named by th
e TRUSTED_PKG_PATH
     environment variable, then the PKG_PATH envi
ronment variable.  The
     special url `installpath' refers to the cont
ents of installurl(5).  If
     neither TRUSTED_PKG_PATH nor PKG_PATH are de
fined, pkg_add will use
     `./:installpath' as a default. "

09.06.2017 12:30 AM "Aaron Bieber" <notifications@github.com> napisał(a):

**Comment by qbit** [comment]
So you have PKG_PATH set everywhere? or install via files?

**Comment by kmonticolo** [comment]
I personally use both, Installurl and PKG_PATH.

10.06.2017 2:55 PM "Aaron Bieber" <notifications@github.com> napisał(a):
