### ISSUE TITLE
Switching to root instead of doas(1)

### ISSUE THREAD

**Issue by Brahmasmi** [qbit/snap#54]
The example usage section [1] of snap seems to suggest using doas(1).

```
$ doas snap -M cdn.openbsd.org
```

Would it be better if we were to suggest becoming root?

I say this because, if I am not wrong, the snap script replicates what the upgrade guide's [2] "Upgrade without the install kernel" section does. That section contains:

"Become root. While using doas(1) before each command is generally a good practice, the command will likely be broken by the last steps, so you should become root before starting this process. It might be good to verify your access to root using a method other than doas at this point, i.e., direct login or using su(1)."

Dhanyavaad.

[1] - https://github.com/qbit/snap#example-usage
[2] - https://www.openbsd.org/faq/upgrade64.html

**Comment by qbit** [comment]
One can call it how ever they want.. the usage is simply to illustrate one needs to elevate privs.

That said, the way displayed in the usage is exactly the same as becoming root first. All the steps the updrage doc mentions are run as root.

This can be illustrated by doing:

```
$ doas sleep 30
# in another terminal:
$ ps auxwww | grep "sleep 30"
root     82226  0.0  0.0   152   120 p6  S+p    7:37AM    0:00.01 sleep 30
```

`doas` executes `sleep` as root and exits.

**Comment by Brahmasmi** [comment]
Understood. Thank you for your illustrative response. I was worried about the "you should become root before starting this process" in the Upgrade FAQ. But from what I now understand, the entire script and its child commands run under root until the script exits. Hence doas(1) suffices.

Dhanyavaad.
